Devel/humble pranav
KumarRobotics/kr_mav_control pull request #158
Opened 2024-02-15 00:09 UTC by pranavpshah

kr_tracker_msgs and kr_mav_msgs ROS2 humble compatible.

2024-02-15 16:29 UTC, fcladera requested changes
Take a look into these

2024-02-15 16:29 UTC, fcladera commented on kr_mav_msgs/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.8)
@pranavpshah

2024-02-15 16:32 UTC, pranavpshah commented on kr_mav_msgs/msg/TRPYCommand.msg
> +float64[3] kr
ROS2 requires only lowercase for msg fieldnames, no camel case.

2024-02-15 16:34 UTC, pranavpshah commented on kr_mav_msgs/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.8)
That is the version that comes up whenever I've used "ros2 pkg create", so I decided to keep the same version to be on the safe side.

2024-02-15 16:35 UTC, pranavpshah commented on kr_mav_msgs/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.8)
It does build with the 3.10 version as well, but since ros2 creates packages with the 3.8 version, I thought it would be a safe choice to have 3.8.

2024-02-15 16:35 UTC, pranavpshah commented on trackers/kr_tracker_msgs/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.8)
Added comment for kr_mav_msgs

2024-02-15 19:25 UTC, fcladera commented on kr_mav_msgs/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.8)
Let's stick to 3.10

2024-02-15 19:27 UTC, pranavpshah commented on kr_mav_msgs/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.8)
Okay, I will push another commit with this change for both the CMakeLists.txt

2024-02-15 19:32 UTC, pranavpshah commented
@fcladera changes to the cmake version have been made as suggested.

2024-02-16 14:33 UTC, fcladera approved these changes

2024-02-16 14:33 UTC, merged